name: uas2022
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0-329.0.dev <3.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  get_cli: ^1.8.1
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  splash_screen_view: ^3.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - "assets/json/BookData.json"
  - "assets/json/Login.json"
  - "assets/image/illustration.png"
  - "assets/image/undraw.svg"
  - "assets/image/undraw.png"
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-light.ttf
        weight: 300
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        weight: 500 
      - asset: assets/fonts/Poppins/Poppins-Black.ttf
        weight: 700 
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        weight: 600 


splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  color: "#ffffff"
  #background_image: "assets/splashscreen_image.png"

  # Optional parameters are listed below.
  #image: assets/splashscreen_image.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'